// Та энд үгийн сангаа өөрөө нэмээд/солиж болно.
// Баримт дээр жишээ threat/neutral үгсийн жагсаалт байгаа :contentReference[oaicite:3]{index=3}

export const THREAT_WORDS: string[] = [
  "PANICKY",
  "DESPERATE",
  "SCARED",
  "CANCER",
  "DANGER",
  "ALARMED",
  "TRAUMA",
  "EMERGENCY",
  "DISTRESS",
  "HOSTILE",
  "FRIGHT",
  "WORRIED",
  "DISEASE",
  "SINISTER",
  "MUTILATED",
  "NERVOUS",
  "ASSAULT",
  "SUFFOCATING",
  "CATASTROPHE",
  "HARM",
  "TENSE",
  "JUMPY",
  "LETHAL",
  "ATTACK",
  "HORROR",
  "STRANGLED",
  "INSECURE",
  "INCURABLE",
  "FUNERAL",
  "TRAGEDY",
];

export const NEUTRAL_WORDS: string[] = [
  "CLARETS",
  "VARIABLE",
  "NECKLACE",
  "EDITIONS",
  "PLANET",
  "SADDLE",
  "SHELVES",
  "RECEIPTS",
  "ENJOIN",
  "RINK",
  "LISTENING",
  "CREATURE",
  "ARRANGED",
  "TINTED",
  "CONTEXT",
  "CONFER",
  "REMARKS",
  "FOLD",
  "INTEGRAL",
  "DECANTING",
  "OUTCOME",
  "BOTTLES",
  "CONSTITUENT",
  "APPROXIMATE",
  "NOON",
  "BACKS",
  "LOTUS",
  "GEOMETRIC",
  "MICROSCOPIC",
  "RACKET",
];

export function clampTrialsPerPhase(n: number) {
  const max = Math.min(THREAT_WORDS.length, NEUTRAL_WORDS.length);
  return Math.max(1, Math.min(n, max));
}
